# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [ 16.20.0 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set secrets as environment variables
        run: |
          echo "SQL_PASSWORD=${{ secrets.SQL_PASSWORD }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "SQL_HOST=${{ secrets.SQL_HOST }}" >> .env
          echo "SQL_DB=${{ secrets.SQL_DB }}" >> .env
          echo "SQL_USER=${{ secrets.SQL_USER }}" >> .env
        working-directory: toff_backend/

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Initialize Frontend
        working-directory: toff_frontend/
        run: npm ci

      - name: Build Frontend
        working-directory: toff_frontend/
        run: npm run build

      - name: Initialize Backend
        working-directory: toff_backend/
        run: npm ci
  deploy:
    runs-on: self-hosted
    needs: build # this job depends on "test" having finished
    steps:
      - name: Deploying to Test Server
        #uses: appleboy/ssh-action@master # An action made to control Linux servers
        uses: actions/setup-node@v3
        with: # We set all our secrets here for the action, these won't be shown in the action logs
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ./toff_portfolio/
            git pull # we pull any changes from git
            cd ./toff_frontend/
            npm install # we install any missing dependencies
            npm run build # we build our app
            cd ../toff_backend/
            npm install
            pm2 reload all # we reload the app via PM2
